// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeTheme(arg1, arg2) {
  return window['go']['main']['App']['ChangeTheme'](arg1, arg2);
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function ConnectCloudServer(arg1) {
  return window['go']['main']['App']['ConnectCloudServer'](arg1);
}

export function FetchCloudServers() {
  return window['go']['main']['App']['FetchCloudServers']();
}

export function ForceReconnect(arg1) {
  return window['go']['main']['App']['ForceReconnect'](arg1);
}

export function GetActivePhoneID() {
  return window['go']['main']['App']['GetActivePhoneID']();
}

export function GetCloudStatus() {
  return window['go']['main']['App']['GetCloudStatus']();
}

export function GetInfo() {
  return window['go']['main']['App']['GetInfo']();
}

export function GetPhoneList() {
  return window['go']['main']['App']['GetPhoneList']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function MinimizeToFloatbar() {
  return window['go']['main']['App']['MinimizeToFloatbar']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ReadClipboard() {
  return window['go']['main']['App']['ReadClipboard']();
}

export function RenamePhone(arg1, arg2) {
  return window['go']['main']['App']['RenamePhone'](arg1, arg2);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function RestartCloud() {
  return window['go']['main']['App']['RestartCloud']();
}

export function RestoreMainWindow() {
  return window['go']['main']['App']['RestoreMainWindow']();
}

export function SelectPhone(arg1) {
  return window['go']['main']['App']['SelectPhone'](arg1);
}

export function Send(arg1, arg2) {
  return window['go']['main']['App']['Send'](arg1, arg2);
}

export function SendDial(arg1) {
  return window['go']['main']['App']['SendDial'](arg1);
}

export function SendHangup() {
  return window['go']['main']['App']['SendHangup']();
}

export function SendSMS(arg1, arg2) {
  return window['go']['main']['App']['SendSMS'](arg1, arg2);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetPin(arg1) {
  return window['go']['main']['App']['SetPin'](arg1);
}

export function SetTopmost(arg1) {
  return window['go']['main']['App']['SetTopmost'](arg1);
}

export function TestCloudServers(arg1) {
  return window['go']['main']['App']['TestCloudServers'](arg1);
}

export function ToggleFloatbar() {
  return window['go']['main']['App']['ToggleFloatbar']();
}

export function UpdateCloudConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateCloudConfig'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
