// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeTheme(arg1:string,arg2:string):Promise<void>;

export function CloseWindow():Promise<void>;

export function ConnectCloudServer(arg1:string):Promise<void>;

export function FetchCloudServers():Promise<Array<string>>;

export function ForceReconnect(arg1:string):Promise<string>;

export function GetActivePhoneID():Promise<string>;

export function GetCloudStatus():Promise<Record<string, any>>;

export function GetInfo():Promise<Record<string, any>>;

export function GetPhoneList():Promise<Array<Record<string, any>>>;

export function GetPlatform():Promise<Record<string, string>>;

export function GetSettings():Promise<Record<string, any>>;

export function MinimizeToFloatbar():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function QuitApp():Promise<void>;

export function ReadClipboard():Promise<Record<string, string>>;

export function RenamePhone(arg1:string,arg2:string):Promise<void>;

export function RestartApp():Promise<void>;

export function RestartCloud():Promise<void>;

export function RestoreMainWindow():Promise<void>;

export function SelectPhone(arg1:string):Promise<void>;

export function Send(arg1:string,arg2:any):Promise<void>;

export function SendDial(arg1:string):Promise<string>;

export function SendHangup():Promise<string>;

export function SendSMS(arg1:string,arg2:string):Promise<string>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetPin(arg1:string):Promise<void>;

export function SetTopmost(arg1:boolean):Promise<void>;

export function TestCloudServers(arg1:Array<string>):Promise<Array<Record<string, any>>>;

export function ToggleFloatbar():Promise<string>;

export function UpdateCloudConfig(arg1:boolean,arg2:Array<string>):Promise<void>;

export function UpdateSettings(arg1:Record<string, any>):Promise<void>;
